name: Rename Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: pip install --upgrade pip

      # Step 4: Run the Python script
      - name: Run rename_files.py
        run: python rename_files.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Renamed files to match naming convention"
          git push

