name: Update README with Wallpapers

on:
  workflow_run:
    workflows:
      - Rename Files
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: pip install --upgrade pip

      # Step 4: Run the Python script
      - name: Run update_readme.py
        run: python scripts/update_readme.py

      # Step 5: Check for changes
      - name: Check for changes
        id: git_status
        run: |
          git add README.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      # Step 6: Commit and push changes (only if there are changes)
      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update README with wallpapers"
          git push

